file:
  in_dir: './data/'
  out_dir: './data/recon/'
  spoke_size: 224
  grid_z: 90
  plane_num: 240
  stage_num: 48
  nChannel: 24
  voxel_size: [2.0,2.0,2.0]

train:
  gpu: 1
  lr: 1.0e-3
  epoch: 120
  save_epoch: 20
  lr_decay_epoch: 20
  lr_decay_rate: 0.5
  batch_size: 1

encoding:
  otype: 'Grid'
  type: 'Hash'
  n_levels: 10 # default 10
  n_features_per_level: 8 # default 8
  log2_hashmap_size: 18 # default 18
  base_resolution: 2 #default 2
  per_level_scale: 2.0
  interpolation: 'Linear'

mlp:
  otype: 'FullyFusedMLP'
  activation: 'ReLU'
  output_activation: 'None' # default 'None'
  n_neurons: 64 # default 128
  n_hidden_layers: 3 # default 8

encoding_csm:
  otype: 'Grid'
  type: 'Hash'
  n_levels: 8
  n_features_per_level: 2   #default 2     
  log2_hashmap_size: 19    # default 19
  base_resolution: 1      #default 16
  per_level_scale: 1.5      #default 2
  interpolation: 'Linear'

mlp_csm:
  otype: 'FullyFusedMLP'           # Component type.
  activation: 'ReLU'               # Activation of hidden layers.
  output_activation: 'None'        # Activation of the output layer.
  n_neurons: 64                    # Neurons in each hidden layer.
                                   # May only be 16, 32, 640, or 128.
  n_hidden_layers: 2               # Number of hidden layers. 